ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.syncfit.plugins.KoinKt.configureKoin
      - com.syncfit.plugins.HttpKt.configureHttp
      - com.syncfit.plugins.SerializationKt.configureSerialization
      - com.syncfit.plugins.ResourcesKt.configureResources
      - com.syncfit.plugins.RoutingKt.configureRouting
      - com.syncfit.plugins.MonitoringKt.configureMonitoring
