package com.syncfit.repository

import com.syncfit.model.ExerciseInfo
import com.syncfit.model.ExerciseInfoApiResponse
import com.syncfit.model.ExerciseType

class ExerciseInfoRepositoryImpl : ExerciseInfoRepository {
    override val exerciseInfoByType: Map<ExerciseType, ExerciseInfo> = mapOf(
        ExerciseType.SQUAT to ExerciseInfo(
            id = 1,
            exerciseName = "Squat",
            exerciseVariations = listOf(
                "Bodyweight Squat",
                "Barbell Back Squat",
                "Barbell Front Squat",
                "Goblet Squat",
                "Dumbbell Squat",
                "Smith Machine Squat",
                "Hack Squat",
            ),
            primaryMuscle = "Quadriceps",
            targetedMuscleGroup = listOf("Quadriceps", "Glutes", "Hamstrings", "Adductors"),
            secondaryMuscle = "Core and lower back",
            equipment = "Barbell and squat rack",
            howToPerform = listOf(
                "Position the bar across your upper back and stand with your feet approximately shoulder-width apart.",
                "Brace your core, keep your chest up, and maintain a neutral spine.",
                "Bend your hips and knees together, keeping your knees aligned with your toes.",
                "Lower under control until your thighs are at least parallel to the floor, or as mobility allows.",
                "Drive through your whole foot and extend your hips and knees to return to standing.",
            ),
            exerciseLevel = "Advanced",
            isAiFormCheckEnabled = true,
            demonstrationLink = "",
        ),
        ExerciseType.BICEP_CURL to ExerciseInfo(
            id = 2,
            exerciseName = "Bicep Curl",
            exerciseVariations = listOf(
                "Barbell Bicep Curl",
                "Dumbbell Bicep Curl",
                "EZ-Bar Curl",
                "Cable Bicep Curl",
                "Resistance Band Curl",
                "Hammer Curl",
                "Preacher Curl",
            ),
            primaryMuscle = "Biceps brachii",
            targetedMuscleGroup = listOf("Biceps brachii", "Brachialis", "Brachioradialis"),
            secondaryMuscle = "Forearm flexors",
            equipment = "Barbell",
            howToPerform = listOf(
                "Stand tall with your feet hip-width apart and hold the bar using an underhand grip.",
                "Brace your core and keep your elbows close to your sides.",
                "Curl the bar toward your shoulders without swinging your torso or moving your upper arms.",
                "Pause briefly at the top while keeping your wrists neutral.",
                "Lower the bar slowly until your elbows are fully extended without locking them forcefully.",
            ),
            exerciseLevel = "Intermediate",
            isAiFormCheckEnabled = false,
            demonstrationLink = "",
        ),
        ExerciseType.DEADLIFT to ExerciseInfo(
            id = 3,
            exerciseName = "Deadlift",
            exerciseVariations = listOf(
                "Conventional Barbell Deadlift",
                "Sumo Deadlift",
                "Romanian Deadlift",
                "Stiff-Leg Deadlift",
                "Trap-Bar Deadlift",
                "Dumbbell Deadlift",
            ),
            primaryMuscle = "Glutes",
            targetedMuscleGroup = listOf("Glutes", "Hamstrings", "Quadriceps", "Erector spinae"),
            secondaryMuscle = "Core, upper back, and forearms",
            equipment = "Barbell and weight plates",
            howToPerform = listOf(
                "Stand with your mid-foot under the bar and your feet approximately hip-width apart.",
                "Hinge at your hips, bend your knees, and grip the bar just outside your legs.",
                "Brace your core, flatten your back, and keep the bar close to your shins.",
                "Push the floor away and extend your knees and hips together until you stand tall.",
                "Hinge at your hips, then bend your knees to return the bar to the floor under control.",
            ),
            exerciseLevel = "Advanced",
            isAiFormCheckEnabled = false,
            demonstrationLink = "",
        ),
        ExerciseType.LATERAL_RAISE to ExerciseInfo(
            id = 4,
            exerciseName = "Lateral Raise",
            exerciseVariations = listOf(
                "Standing Dumbbell Lateral Raise",
                "Seated Dumbbell Lateral Raise",
                "Cable Lateral Raise",
                "Machine Lateral Raise",
                "Resistance Band Lateral Raise",
                "Leaning Lateral Raise",
            ),
            primaryMuscle = "Lateral deltoids",
            targetedMuscleGroup = listOf("Lateral deltoids", "Anterior deltoids"),
            secondaryMuscle = "Upper trapezius and rotator cuff",
            equipment = "Dumbbells",
            howToPerform = listOf(
                "Stand tall with a dumbbell in each hand and your arms resting by your sides.",
                "Brace your core and keep a slight bend in your elbows.",
                "Raise your arms out to the sides without shrugging or swinging the weights.",
                "Stop near shoulder height with your wrists in a neutral position.",
                "Lower the dumbbells slowly to the starting position.",
            ),
            exerciseLevel = "Beginner",
            isAiFormCheckEnabled = false,
            demonstrationLink = "",
        ),
        ExerciseType.FLAT_CHEST_PRESS to ExerciseInfo(
            id = 5,
            exerciseName = "Flat Chest Press",
            exerciseVariations = listOf(
                "Flat Barbell Chest Press",
                "Flat Dumbbell Chest Press",
                "Flat Machine Chest Press",
                "Smith Machine Chest Press",
                "Flat Cable Chest Press",
            ),
            primaryMuscle = "Pectoralis major",
            targetedMuscleGroup = listOf("Pectoralis major", "Anterior deltoids", "Triceps"),
            secondaryMuscle = "Serratus anterior and upper back stabilizers",
            equipment = "Barbell, flat bench, and rack",
            howToPerform = listOf(
                "Lie on the bench with your eyes under the bar and keep both feet planted on the floor.",
                "Grip the bar slightly wider than shoulder-width and draw your shoulder blades back and down.",
                "Unrack the bar and position it over your chest with your wrists stacked above your elbows.",
                "Lower the bar under control toward your mid-chest while keeping your forearms nearly vertical.",
                "Press the bar upward until your arms are extended without lifting your shoulders from the bench.",
            ),
            exerciseLevel = "Intermediate",
            isAiFormCheckEnabled = false,
            demonstrationLink = "",
        ),
        ExerciseType.INCLINE_CHEST_PRESS to ExerciseInfo(
            id = 6,
            exerciseName = "Incline Chest Press",
            exerciseVariations = listOf(
                "Incline Dumbbell Chest Press",
                "Incline Barbell Chest Press",
                "Incline Machine Chest Press",
                "Incline Smith Machine Press",
                "Incline Cable Chest Press",
            ),
            primaryMuscle = "Upper pectoralis major",
            targetedMuscleGroup = listOf("Upper pectoralis major", "Anterior deltoids", "Triceps"),
            secondaryMuscle = "Serratus anterior and upper back stabilizers",
            equipment = "Dumbbells and incline bench",
            howToPerform = listOf(
                "Set the bench to a low incline and sit with one dumbbell resting on each thigh.",
                "Lie back, plant your feet, and position the dumbbells beside your upper chest.",
                "Draw your shoulder blades back and down while keeping your wrists above your elbows.",
                "Press the dumbbells upward until your arms are extended without letting your shoulders roll forward.",
                "Lower the dumbbells slowly until your elbows are slightly below chest level, as comfort allows.",
            ),
            exerciseLevel = "Beginner",
            isAiFormCheckEnabled = false,
            demonstrationLink = "",
        ),
        ExerciseType.LEG_PRESS to ExerciseInfo(
            id = 7,
            exerciseName = "Leg Press",
            exerciseVariations = listOf(
                "45-Degree Leg Press",
                "Horizontal Seated Leg Press",
                "Vertical Leg Press",
                "Single-Leg Press",
            ),
            primaryMuscle = "Quadriceps",
            targetedMuscleGroup = listOf("Quadriceps", "Glutes", "Hamstrings"),
            secondaryMuscle = "Adductors and calves",
            equipment = "Leg press machine",
            howToPerform = listOf(
                "Adjust the seat so your back and hips remain supported throughout the movement.",
                "Place your feet approximately shoulder-width apart on the platform with your knees aligned over your toes.",
                "Release the safety handles and lower the platform by bending your knees under control.",
                "Stop before your lower back or hips begin to lift away from the pad.",
                "Press through your whole feet to extend your legs without forcefully locking your knees.",
            ),
            exerciseLevel = "Beginner",
            isAiFormCheckEnabled = false,
            demonstrationLink = "",
        ),
        ExerciseType.SHOULDER_PRESS to ExerciseInfo(
            id = 8,
            exerciseName = "Shoulder Press",
            exerciseVariations = listOf(
                "Seated Dumbbell Shoulder Press",
                "Standing Dumbbell Shoulder Press",
                "Barbell Overhead Press",
                "Machine Shoulder Press",
                "Smith Machine Shoulder Press",
                "Arnold Press",
                "Landmine Press",
            ),
            primaryMuscle = "Deltoids",
            targetedMuscleGroup = listOf("Anterior deltoids", "Lateral deltoids", "Triceps"),
            secondaryMuscle = "Upper trapezius and core",
            equipment = "Dumbbells",
            howToPerform = listOf(
                "Sit or stand tall with a dumbbell in each hand at shoulder height.",
                "Brace your core, keep your ribs controlled, and position your wrists above your elbows.",
                "Press the dumbbells overhead without excessively arching your lower back.",
                "Finish with your arms extended while keeping your shoulders away from your ears.",
                "Lower the dumbbells under control back to shoulder height.",
            ),
            exerciseLevel = "Intermediate",
            isAiFormCheckEnabled = false,
            demonstrationLink = "",
        ),
        ExerciseType.TRICEP_EXTENSION to ExerciseInfo(
            id = 9,
            exerciseName = "Tricep Extension",
            exerciseVariations = listOf(
                "Straight-Bar Cable Pushdown",
                "Rope Cable Pushdown",
                "V-Bar Cable Pushdown",
                "Overhead Cable Tricep Extension",
                "Dumbbell Overhead Tricep Extension",
                "Lying Barbell Tricep Extension",
                "Lying EZ-Bar Tricep Extension",
            ),
            primaryMuscle = "Triceps brachii",
            targetedMuscleGroup = listOf("Triceps long head", "Triceps lateral head", "Triceps medial head"),
            secondaryMuscle = "Forearms, shoulders, and core",
            equipment = "Cable machine and straight-bar attachment",
            howToPerform = listOf(
                "Attach a straight bar to a high cable pulley and hold it with an overhand grip.",
                "Stand tall with a slight bend in your knees, brace your core, and keep your elbows beside your torso.",
                "Extend your elbows and press the bar downward without moving your upper arms.",
                "Pause briefly with your arms extended while keeping your wrists neutral.",
                "Allow the bar to rise slowly until your forearms approach your upper arms, then repeat.",
            ),
            exerciseLevel = "Beginner",
            isAiFormCheckEnabled = false,
            demonstrationLink = "",
        ),
    )

    override suspend fun getExerciseInfo(exerciseName: String): ExerciseInfoApiResponse {
        val exerciseType = ExerciseType.entries.firstOrNull {
            it.name.equals(exerciseName.trim(), ignoreCase = true)
        } ?: return ExerciseInfoApiResponse(
            success = false,
            message = "Exercise not found: $exerciseName",
        )

        val exerciseInfo = exerciseInfoByType[exerciseType]
            ?: return ExerciseInfoApiResponse(
                success = false,
                message = "Exercise information is unavailable: ${exerciseType.name}",
            )

        return ExerciseInfoApiResponse(
            success = true,
            message = "Exercise Info API Success",
            exerciseInfo = exerciseInfo,
        )
    }
}
